version: 2.1
jobs:
  bootstrap-build:
    docker:
      - image: codesmithy/gcc-bootstrap-build-prerequisites:0.14.0
    steps:
      - run: 
          name: "Set NUIME_ROOT environment variables"
          command: echo 'export NUIME_ROOT="/workspace/projects/nuime"' >> $BASH_ENV
      - checkout:
          path: /workspace/projects/nuime/build-files
      - run:
          name: Build
          command: cd /workspace/projects/nuime/build-files/build-files/gnumake && make
      - run:
          name: Test build
          command: cd /workspace/projects/nuime/build-files/tests/build-files/gnumake && make
      - run:
          name: Run the tests
          command: cd /workspace/projects/nuime/build-files/tests/build-files/gnumake && ./nuime_buildfiles_tests --persistent-storage=/build/test-output --junit-xml-test-report=/build/test-results/NuimeBuildFiles.xml
      - store_artifacts:
          name: Upload test output files
          path: /build/test-output
          destination: test-output
      - store_artifacts:
          name: Upload test report files
          path: /build/test-results/NuimeBuildFiles.xml
          destination: NuimeBuildFiles-test-results.xml
      - store_test_results:
          name: Upload test results to CircleCI
          path: /build/test-results/NuimeBuildFiles.xml
  build:
    docker:
      - image: codesmithy/gcc-build-prerequisites:0.18.0
    steps:
      - run:
          name: "Set NUIME_ROOT environment variables"
          command: echo 'export NUIME_ROOT="/workspace/projects/nuime"' >> $BASH_ENV
      - checkout:
          path: /workspace/projects/nuime/build-files
      - run:
          name: Build
          command: cd /workspace/projects/nuime/build-files/build-files/gnumake && make
      - run:
          name: Test build
          command: cd /workspace/projects/nuime/build-files/tests/build-files/gnumake && make
      - run:
          name: Run the tests
          command: cd /workspace/projects/nuime/build-files/tests/build-files/gnumake && ./nuime_buildfiles_tests --persistent-storage=/build/test-output --junit-xml-test-report=/build/test-results/NuimeBuildFiles.xml
      - store_artifacts:
          name: Upload test output files
          path: /build/test-output
          destination: test-output
      - store_artifacts:
          name: Upload test report files
          path: /build/test-results/NuimeBuildFiles.xml
          destination: NuimeBuildFiles-test-results.xml
      - store_test_results:
          name: Upload test results to CircleCI
          path: /build/test-results/NuimeBuildFiles.xml
workflows:
  version: 2
  continuous_build:
    jobs:
      - bootstrap-build
      - build
  weekly_build:
    jobs:
      - bootstrap-build
      - build
    triggers:
      - schedule:
          cron: "0 8 * * 0"
          filters:
            branches:
              only:
                 - main
