version: 2
jobs:
  bootstrap-build:
    docker:
      - image: codesmithy/gcc-bootstrap-build-prerequisites:0.6.0
    steps:
      - run: 
          name: "Set CODESMITHYIDE_ROOT environment variables"
          command: echo 'export CODESMITHYIDE_ROOT="/codesmithyide"' >> $BASH_ENV
      - checkout:
          path: /codesmithyide/build-files
      - run:
          name: Build
          command: cd /codesmithyide/build-files/build/gnumake && make
      - run:
          name: Test build
          command: cd /codesmithyide/build-files/tests/build/gnumake && make
      - run:
          name: Run the tests
          command: cd /codesmithyide/build-files/tests/build/gnumake && ./CodeSmithyBuildFilesTests --persistent-storage=/build/test-output --junit-xml-test-report=/build/test-results/CodeSmithyBuildFiles.xml
      - store_artifacts:
          name: Upload test output files
          path: /build/test-output
          destination: test-output
      - store_artifacts:
          name: Upload test report files
          path: /build/test-results/CodeSmithyBuildFiles.xml
          destination: CodeSmithyBuildFiles-test-results.xml
      - store_test_results:
          name: Upload test results to CircleCI
          path: /build/test-results/CodeSmithyBuildFiles.xml
  build:
    docker:
      - image: codesmithy/gcc-build-prerequisites:0.8.0
    steps:
      - run:
          name: "Set CODESMITHYIDE_ROOT environment variables"
          command: echo 'export CODESMITHYIDE_ROOT="/codesmithyide"' >> $BASH_ENV
      - checkout:
          path: /codesmithyide/build-files
      - run:
          name: Build
          command: cd /codesmithyide/build-files/build/gnumake && make
      - run:
          name: Test build
          command: cd /codesmithyide/build-files/tests/build/gnumake && make
      - run:
          name: Run the tests
          command: cd /codesmithyide/build-files/tests/build/gnumake && ./CodeSmithyBuildFilesTests --persistent-storage=/build/test-output --junit-xml-test-report=/build/test-results/CodeSmithyBuildFiles.xml
      - store_artifacts:
          name: Upload test output files
          path: /build/test-output
          destination: test-output
      - store_artifacts:
          name: Upload test report files
          path: /build/test-results/CodeSmithyBuildFiles.xml
          destination: CodeSmithyBuildFiles-test-results.xml
      - store_test_results:
          name: Upload test results to CircleCI
          path: /build/test-results/CodeSmithyBuildFiles.xml
workflows:
  version: 2
  continuous_build:
    jobs:
      - bootstrap-build
      - build
  weekly_build:
    jobs:
      - bootstrap-build
      - build
    triggers:
      - schedule:
          cron: "0 8 * * 0"
          filters:
            branches:
              only:
                 - main
